# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdParser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdParser.proto',
  package='bot',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63mdParser.proto\x12\x03\x62ot\"\x15\n\x06\x42otCmd\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\"\x1f\n\nBotCmdResp\x12\x11\n\tparsedcmd\x18\x01 \x01(\t2;\n\x10\x42otCommandParser\x12\'\n\x05Parse\x12\x0b.bot.BotCmd\x1a\x0f.bot.BotCmdResp\"\x00\x42*\n\x13\x63om.cisco.spark.botB\x11\x42otCmdParserProtoP\x01\x62\x06proto3')
)




_BOTCMD = _descriptor.Descriptor(
  name='BotCmd',
  full_name='bot.BotCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='bot.BotCmd.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)


_BOTCMDRESP = _descriptor.Descriptor(
  name='BotCmdResp',
  full_name='bot.BotCmdResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parsedcmd', full_name='bot.BotCmdResp.parsedcmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['BotCmd'] = _BOTCMD
DESCRIPTOR.message_types_by_name['BotCmdResp'] = _BOTCMDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BotCmd = _reflection.GeneratedProtocolMessageType('BotCmd', (_message.Message,), dict(
  DESCRIPTOR = _BOTCMD,
  __module__ = 'cmdParser_pb2'
  # @@protoc_insertion_point(class_scope:bot.BotCmd)
  ))
_sym_db.RegisterMessage(BotCmd)

BotCmdResp = _reflection.GeneratedProtocolMessageType('BotCmdResp', (_message.Message,), dict(
  DESCRIPTOR = _BOTCMDRESP,
  __module__ = 'cmdParser_pb2'
  # @@protoc_insertion_point(class_scope:bot.BotCmdResp)
  ))
_sym_db.RegisterMessage(BotCmdResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.cisco.spark.botB\021BotCmdParserProtoP\001'))

_BOTCOMMANDPARSER = _descriptor.ServiceDescriptor(
  name='BotCommandParser',
  full_name='bot.BotCommandParser',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=80,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='bot.BotCommandParser.Parse',
    index=0,
    containing_service=None,
    input_type=_BOTCMD,
    output_type=_BOTCMDRESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOTCOMMANDPARSER)

DESCRIPTOR.services_by_name['BotCommandParser'] = _BOTCOMMANDPARSER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class BotCommandParserStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Parse = channel.unary_unary(
          '/bot.BotCommandParser/Parse',
          request_serializer=BotCmd.SerializeToString,
          response_deserializer=BotCmdResp.FromString,
          )


  class BotCommandParserServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Parse(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_BotCommandParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Parse': grpc.unary_unary_rpc_method_handler(
            servicer.Parse,
            request_deserializer=BotCmd.FromString,
            response_serializer=BotCmdResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'bot.BotCommandParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaBotCommandParserServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Parse(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaBotCommandParserStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Parse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Parse.future = None


  def beta_create_BotCommandParser_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('bot.BotCommandParser', 'Parse'): BotCmd.FromString,
    }
    response_serializers = {
      ('bot.BotCommandParser', 'Parse'): BotCmdResp.SerializeToString,
    }
    method_implementations = {
      ('bot.BotCommandParser', 'Parse'): face_utilities.unary_unary_inline(servicer.Parse),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_BotCommandParser_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('bot.BotCommandParser', 'Parse'): BotCmd.SerializeToString,
    }
    response_deserializers = {
      ('bot.BotCommandParser', 'Parse'): BotCmdResp.FromString,
    }
    cardinalities = {
      'Parse': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'bot.BotCommandParser', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
