# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cmdParser_pb2 as cmdParser__pb2


class BotCommandParserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Parse = channel.unary_unary(
        '/bot.BotCommandParser/Parse',
        request_serializer=cmdParser__pb2.BotCmd.SerializeToString,
        response_deserializer=cmdParser__pb2.BotCmdResp.FromString,
        )


class BotCommandParserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Parse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BotCommandParserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Parse': grpc.unary_unary_rpc_method_handler(
          servicer.Parse,
          request_deserializer=cmdParser__pb2.BotCmd.FromString,
          response_serializer=cmdParser__pb2.BotCmdResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bot.BotCommandParser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
