# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import generalTA_pb2 as generalTA__pb2


class generalTAStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.exitMe = channel.unary_unary(
        '/generalTA.generalTA/exitMe',
        request_serializer=generalTA__pb2.exitRequest.SerializeToString,
        response_deserializer=generalTA__pb2.exitResponse.FromString,
        )


class generalTAServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def exitMe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_generalTAServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'exitMe': grpc.unary_unary_rpc_method_handler(
          servicer.exitMe,
          request_deserializer=generalTA__pb2.exitRequest.FromString,
          response_serializer=generalTA__pb2.exitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'generalTA.generalTA', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
