# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toolManager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='toolManager.proto',
  package='toolManager',
  syntax='proto3',
  serialized_pb=_b('\n\x11toolManager.proto\x12\x0btoolManager\"m\n\x15managedProcessRequest\x12\x11\n\townerName\x18\x01 \x01(\t\x12\x10\n\x08ownerURL\x18\x02 \x01(\t\x12\x10\n\x08procPath\x18\x03 \x01(\t\x12\x0f\n\x07procNum\x18\x04 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t\"9\n\x16managedProcessResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\"J\n\x17unmanagedProcessRequest\x12\x10\n\x08procPath\x18\x01 \x01(\t\x12\x0f\n\x07procNum\x18\x02 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\";\n\x18unmanagedProcessResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\"\x8d\x01\n\x12managedToolRequest\x12\x11\n\townerName\x18\x01 \x01(\t\x12\x10\n\x08ownerURL\x18\x02 \x01(\t\x12\x10\n\x08toolPath\x18\x03 \x01(\t\x12\x10\n\x08toolType\x18\x04 \x01(\t\x12\x0f\n\x07toolNum\x18\x05 \x01(\x05\x12\x0f\n\x07timeout\x18\x06 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x07 \x03(\t\"6\n\x13managedToolResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\"j\n\x14unmanagedToolRequest\x12\x10\n\x08toolPath\x18\x01 \x01(\t\x12\x10\n\x08toolType\x18\x02 \x01(\t\x12\x0f\n\x07toolNum\x18\x03 \x01(\x05\x12\x0f\n\x07timeout\x18\x04 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t\"8\n\x15unmanagedToolResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x12\x0e\n\x06retMsg\x18\x02 \x01(\t2\x87\x03\n\x0btoolManager\x12^\n\x11runManagedProcess\x12\".toolManager.managedProcessRequest\x1a#.toolManager.managedProcessResponse\"\x00\x12\x64\n\x13runUnmanagedProcess\x12$.toolManager.unmanagedProcessRequest\x1a%.toolManager.unmanagedProcessResponse\"\x00\x12U\n\x0erunManagedTool\x12\x1f.toolManager.managedToolRequest\x1a .toolManager.managedToolResponse\"\x00\x12[\n\x10runUnmanagedTool\x12!.toolManager.unmanagedToolRequest\x1a\".toolManager.unmanagedToolResponse\"\x00\x62\x06proto3')
)




_MANAGEDPROCESSREQUEST = _descriptor.Descriptor(
  name='managedProcessRequest',
  full_name='toolManager.managedProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerName', full_name='toolManager.managedProcessRequest.ownerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ownerURL', full_name='toolManager.managedProcessRequest.ownerURL', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procPath', full_name='toolManager.managedProcessRequest.procPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procNum', full_name='toolManager.managedProcessRequest.procNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='toolManager.managedProcessRequest.args', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=143,
)


_MANAGEDPROCESSRESPONSE = _descriptor.Descriptor(
  name='managedProcessResponse',
  full_name='toolManager.managedProcessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='toolManager.managedProcessResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='toolManager.managedProcessResponse.retMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=202,
)


_UNMANAGEDPROCESSREQUEST = _descriptor.Descriptor(
  name='unmanagedProcessRequest',
  full_name='toolManager.unmanagedProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='procPath', full_name='toolManager.unmanagedProcessRequest.procPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procNum', full_name='toolManager.unmanagedProcessRequest.procNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='toolManager.unmanagedProcessRequest.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=278,
)


_UNMANAGEDPROCESSRESPONSE = _descriptor.Descriptor(
  name='unmanagedProcessResponse',
  full_name='toolManager.unmanagedProcessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='toolManager.unmanagedProcessResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='toolManager.unmanagedProcessResponse.retMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=339,
)


_MANAGEDTOOLREQUEST = _descriptor.Descriptor(
  name='managedToolRequest',
  full_name='toolManager.managedToolRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerName', full_name='toolManager.managedToolRequest.ownerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ownerURL', full_name='toolManager.managedToolRequest.ownerURL', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toolPath', full_name='toolManager.managedToolRequest.toolPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toolType', full_name='toolManager.managedToolRequest.toolType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toolNum', full_name='toolManager.managedToolRequest.toolNum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='toolManager.managedToolRequest.timeout', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='toolManager.managedToolRequest.args', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=483,
)


_MANAGEDTOOLRESPONSE = _descriptor.Descriptor(
  name='managedToolResponse',
  full_name='toolManager.managedToolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='toolManager.managedToolResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='toolManager.managedToolResponse.retMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=539,
)


_UNMANAGEDTOOLREQUEST = _descriptor.Descriptor(
  name='unmanagedToolRequest',
  full_name='toolManager.unmanagedToolRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='toolPath', full_name='toolManager.unmanagedToolRequest.toolPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toolType', full_name='toolManager.unmanagedToolRequest.toolType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toolNum', full_name='toolManager.unmanagedToolRequest.toolNum', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='toolManager.unmanagedToolRequest.timeout', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='toolManager.unmanagedToolRequest.args', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=647,
)


_UNMANAGEDTOOLRESPONSE = _descriptor.Descriptor(
  name='unmanagedToolResponse',
  full_name='toolManager.unmanagedToolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='toolManager.unmanagedToolResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='toolManager.unmanagedToolResponse.retMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=705,
)

DESCRIPTOR.message_types_by_name['managedProcessRequest'] = _MANAGEDPROCESSREQUEST
DESCRIPTOR.message_types_by_name['managedProcessResponse'] = _MANAGEDPROCESSRESPONSE
DESCRIPTOR.message_types_by_name['unmanagedProcessRequest'] = _UNMANAGEDPROCESSREQUEST
DESCRIPTOR.message_types_by_name['unmanagedProcessResponse'] = _UNMANAGEDPROCESSRESPONSE
DESCRIPTOR.message_types_by_name['managedToolRequest'] = _MANAGEDTOOLREQUEST
DESCRIPTOR.message_types_by_name['managedToolResponse'] = _MANAGEDTOOLRESPONSE
DESCRIPTOR.message_types_by_name['unmanagedToolRequest'] = _UNMANAGEDTOOLREQUEST
DESCRIPTOR.message_types_by_name['unmanagedToolResponse'] = _UNMANAGEDTOOLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

managedProcessRequest = _reflection.GeneratedProtocolMessageType('managedProcessRequest', (_message.Message,), dict(
  DESCRIPTOR = _MANAGEDPROCESSREQUEST,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.managedProcessRequest)
  ))
_sym_db.RegisterMessage(managedProcessRequest)

managedProcessResponse = _reflection.GeneratedProtocolMessageType('managedProcessResponse', (_message.Message,), dict(
  DESCRIPTOR = _MANAGEDPROCESSRESPONSE,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.managedProcessResponse)
  ))
_sym_db.RegisterMessage(managedProcessResponse)

unmanagedProcessRequest = _reflection.GeneratedProtocolMessageType('unmanagedProcessRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNMANAGEDPROCESSREQUEST,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.unmanagedProcessRequest)
  ))
_sym_db.RegisterMessage(unmanagedProcessRequest)

unmanagedProcessResponse = _reflection.GeneratedProtocolMessageType('unmanagedProcessResponse', (_message.Message,), dict(
  DESCRIPTOR = _UNMANAGEDPROCESSRESPONSE,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.unmanagedProcessResponse)
  ))
_sym_db.RegisterMessage(unmanagedProcessResponse)

managedToolRequest = _reflection.GeneratedProtocolMessageType('managedToolRequest', (_message.Message,), dict(
  DESCRIPTOR = _MANAGEDTOOLREQUEST,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.managedToolRequest)
  ))
_sym_db.RegisterMessage(managedToolRequest)

managedToolResponse = _reflection.GeneratedProtocolMessageType('managedToolResponse', (_message.Message,), dict(
  DESCRIPTOR = _MANAGEDTOOLRESPONSE,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.managedToolResponse)
  ))
_sym_db.RegisterMessage(managedToolResponse)

unmanagedToolRequest = _reflection.GeneratedProtocolMessageType('unmanagedToolRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNMANAGEDTOOLREQUEST,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.unmanagedToolRequest)
  ))
_sym_db.RegisterMessage(unmanagedToolRequest)

unmanagedToolResponse = _reflection.GeneratedProtocolMessageType('unmanagedToolResponse', (_message.Message,), dict(
  DESCRIPTOR = _UNMANAGEDTOOLRESPONSE,
  __module__ = 'toolManager_pb2'
  # @@protoc_insertion_point(class_scope:toolManager.unmanagedToolResponse)
  ))
_sym_db.RegisterMessage(unmanagedToolResponse)



_TOOLMANAGER = _descriptor.ServiceDescriptor(
  name='toolManager',
  full_name='toolManager.toolManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=708,
  serialized_end=1099,
  methods=[
  _descriptor.MethodDescriptor(
    name='runManagedProcess',
    full_name='toolManager.toolManager.runManagedProcess',
    index=0,
    containing_service=None,
    input_type=_MANAGEDPROCESSREQUEST,
    output_type=_MANAGEDPROCESSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='runUnmanagedProcess',
    full_name='toolManager.toolManager.runUnmanagedProcess',
    index=1,
    containing_service=None,
    input_type=_UNMANAGEDPROCESSREQUEST,
    output_type=_UNMANAGEDPROCESSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='runManagedTool',
    full_name='toolManager.toolManager.runManagedTool',
    index=2,
    containing_service=None,
    input_type=_MANAGEDTOOLREQUEST,
    output_type=_MANAGEDTOOLRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='runUnmanagedTool',
    full_name='toolManager.toolManager.runUnmanagedTool',
    index=3,
    containing_service=None,
    input_type=_UNMANAGEDTOOLREQUEST,
    output_type=_UNMANAGEDTOOLRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOOLMANAGER)

DESCRIPTOR.services_by_name['toolManager'] = _TOOLMANAGER

# @@protoc_insertion_point(module_scope)
