# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vmMonitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vmMonitor.proto',
  package='vmMonitor',
  syntax='proto3',
  serialized_pb=_b('\n\x0fvmMonitor.proto\x12\tvmMonitor\"\x11\n\x0fvmStatusRequest\"b\n\x08vmStatus\x12\x12\n\ncpuPercent\x18\x01 \x01(\x02\x12\x18\n\x10\x63puPercentPerCpu\x18\x02 \x01(\t\x12\x13\n\x0bvmemPercent\x18\x03 \x01(\x02\x12\x13\n\x0bsmemPercent\x18\x04 \x01(\x02\"\x14\n\x12sparkStatusRequest\"\xc5\x01\n\x0bsparkStatus\x12\x0f\n\x07isAlive\x18\x01 \x01(\x08\x12\x12\n\nisLoggedIn\x18\x02 \x01(\x08\x12\x14\n\x0cloggedInUser\x18\x03 \x01(\t\x12\x16\n\x0epairedDeviceId\x18\x04 \x01(\t\x12\x11\n\tcallState\x18\x05 \x01(\t\x12\x11\n\tisInLobby\x18\x06 \x01(\x08\x12\x14\n\x0csparkVersion\x18\x07 \x01(\t\x12\x12\n\nmediaStats\x18\x08 \x01(\t\x12\x13\n\x0bpacketStats\x18\t \x01(\t2\x98\x01\n\tvmMonitor\x12@\n\x0bgetVMStatus\x12\x1a.vmMonitor.vmStatusRequest\x1a\x13.vmMonitor.vmStatus\"\x00\x12I\n\x0egetSparkStatus\x12\x1d.vmMonitor.sparkStatusRequest\x1a\x16.vmMonitor.sparkStatus\"\x00\x62\x06proto3')
)




_VMSTATUSREQUEST = _descriptor.Descriptor(
  name='vmStatusRequest',
  full_name='vmMonitor.vmStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=47,
)


_VMSTATUS = _descriptor.Descriptor(
  name='vmStatus',
  full_name='vmMonitor.vmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuPercent', full_name='vmMonitor.vmStatus.cpuPercent', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpuPercentPerCpu', full_name='vmMonitor.vmStatus.cpuPercentPerCpu', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vmemPercent', full_name='vmMonitor.vmStatus.vmemPercent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='smemPercent', full_name='vmMonitor.vmStatus.smemPercent', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=147,
)


_SPARKSTATUSREQUEST = _descriptor.Descriptor(
  name='sparkStatusRequest',
  full_name='vmMonitor.sparkStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=169,
)


_SPARKSTATUS = _descriptor.Descriptor(
  name='sparkStatus',
  full_name='vmMonitor.sparkStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isAlive', full_name='vmMonitor.sparkStatus.isAlive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isLoggedIn', full_name='vmMonitor.sparkStatus.isLoggedIn', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loggedInUser', full_name='vmMonitor.sparkStatus.loggedInUser', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pairedDeviceId', full_name='vmMonitor.sparkStatus.pairedDeviceId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='callState', full_name='vmMonitor.sparkStatus.callState', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isInLobby', full_name='vmMonitor.sparkStatus.isInLobby', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparkVersion', full_name='vmMonitor.sparkStatus.sparkVersion', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mediaStats', full_name='vmMonitor.sparkStatus.mediaStats', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packetStats', full_name='vmMonitor.sparkStatus.packetStats', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=369,
)

DESCRIPTOR.message_types_by_name['vmStatusRequest'] = _VMSTATUSREQUEST
DESCRIPTOR.message_types_by_name['vmStatus'] = _VMSTATUS
DESCRIPTOR.message_types_by_name['sparkStatusRequest'] = _SPARKSTATUSREQUEST
DESCRIPTOR.message_types_by_name['sparkStatus'] = _SPARKSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vmStatusRequest = _reflection.GeneratedProtocolMessageType('vmStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _VMSTATUSREQUEST,
  __module__ = 'vmMonitor_pb2'
  # @@protoc_insertion_point(class_scope:vmMonitor.vmStatusRequest)
  ))
_sym_db.RegisterMessage(vmStatusRequest)

vmStatus = _reflection.GeneratedProtocolMessageType('vmStatus', (_message.Message,), dict(
  DESCRIPTOR = _VMSTATUS,
  __module__ = 'vmMonitor_pb2'
  # @@protoc_insertion_point(class_scope:vmMonitor.vmStatus)
  ))
_sym_db.RegisterMessage(vmStatus)

sparkStatusRequest = _reflection.GeneratedProtocolMessageType('sparkStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPARKSTATUSREQUEST,
  __module__ = 'vmMonitor_pb2'
  # @@protoc_insertion_point(class_scope:vmMonitor.sparkStatusRequest)
  ))
_sym_db.RegisterMessage(sparkStatusRequest)

sparkStatus = _reflection.GeneratedProtocolMessageType('sparkStatus', (_message.Message,), dict(
  DESCRIPTOR = _SPARKSTATUS,
  __module__ = 'vmMonitor_pb2'
  # @@protoc_insertion_point(class_scope:vmMonitor.sparkStatus)
  ))
_sym_db.RegisterMessage(sparkStatus)



_VMMONITOR = _descriptor.ServiceDescriptor(
  name='vmMonitor',
  full_name='vmMonitor.vmMonitor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=372,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='getVMStatus',
    full_name='vmMonitor.vmMonitor.getVMStatus',
    index=0,
    containing_service=None,
    input_type=_VMSTATUSREQUEST,
    output_type=_VMSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getSparkStatus',
    full_name='vmMonitor.vmMonitor.getSparkStatus',
    index=1,
    containing_service=None,
    input_type=_SPARKSTATUSREQUEST,
    output_type=_SPARKSTATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VMMONITOR)

DESCRIPTOR.services_by_name['vmMonitor'] = _VMMONITOR

# @@protoc_insertion_point(module_scope)
