# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resManager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resManager.proto',
  package='resAdmin',
  syntax='proto3',
  serialized_pb=_b('\n\x10resManager.proto\x12\x08resAdmin\"3\n\x0ereleaseRequest\x12\x0f\n\x07jobUUID\x18\x01 \x01(\t\x12\x10\n\x08occupier\x18\x02 \x01(\t\"\"\n\x0freleaseResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\"[\n\x0ereserveRequest\x12\x0e\n\x06resNum\x18\x01 \x01(\x05\x12\x10\n\x08occupier\x18\x02 \x01(\t\x12\x16\n\x0ereserveSeconds\x18\x03 \x01(\x05\x12\x0f\n\x07jobUUID\x18\x04 \x01(\t\"\x8b\x01\n\x0freserveResponse\x12\x32\n\x07retCode\x18\x01 \x01(\x0e\x32!.resAdmin.reserveResponse.RetCode\x12\x0e\n\x06IPList\x18\x02 \x03(\t\"4\n\x07RetCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bNO_RESOURCE\x10\x03\"\x8d\x02\n\rresStatusInfo\x12\x0f\n\x07resType\x18\x01 \x01(\t\x12\r\n\x05resIP\x18\x02 \x01(\t\x12\x34\n\tresStatus\x18\x03 \x01(\x0e\x32!.resAdmin.resStatusInfo.ResStatus\x12\x10\n\x08occupier\x18\x04 \x01(\t\x12\x1d\n\x15occupyExpireTimeStamp\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x0f\n\x07jobUUID\x18\x07 \x01(\t\"Q\n\tResStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\x0b\n\x07PENDING\x10\x02\x12\x0c\n\x08OCCUPIED\x10\x03\x12\r\n\tRELEASING\x10\x04\"\x07\n\x05\x45mpty\"0\n\x11resGetResPoolInfo\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04\x66ree\x18\x02 \x01(\x05\"\x1d\n\x0cresAgentInfo\x12\r\n\x05resIP\x18\x01 \x01(\t\"\x1c\n\theartBeat\x12\x0f\n\x07isAlive\x18\x01 \x01(\x08\x32\xe6\x02\n\nresManager\x12G\n\x0ereserveWindows\x12\x18.resAdmin.reserveRequest\x1a\x19.resAdmin.reserveResponse\"\x00\x12G\n\x0ereleaseWindows\x12\x18.resAdmin.releaseRequest\x1a\x19.resAdmin.releaseResponse\"\x00\x12\x43\n\rupdateResPool\x12\x17.resAdmin.resStatusInfo\x1a\x17.resAdmin.resStatusInfo\"\x00\x12@\n\x0egetResPoolInfo\x12\x0f.resAdmin.Empty\x1a\x1b.resAdmin.resGetResPoolInfo\"\x00\x12?\n\x0e\x63heckHeartBeat\x12\x16.resAdmin.resAgentInfo\x1a\x13.resAdmin.heartBeat\"\x00\x42\x30\n\x1bio.grpc.resAdmin.resManagerB\nresManagerP\x01\xa2\x02\x02RAb\x06proto3')
)



_RESERVERESPONSE_RETCODE = _descriptor.EnumDescriptor(
  name='RetCode',
  full_name='resAdmin.reserveResponse.RetCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_RESOURCE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=300,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_RESERVERESPONSE_RETCODE)

_RESSTATUSINFO_RESSTATUS = _descriptor.EnumDescriptor(
  name='ResStatus',
  full_name='resAdmin.resStatusInfo.ResStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVAILABLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OCCUPIED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASING', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=543,
  serialized_end=624,
)
_sym_db.RegisterEnumDescriptor(_RESSTATUSINFO_RESSTATUS)


_RELEASEREQUEST = _descriptor.Descriptor(
  name='releaseRequest',
  full_name='resAdmin.releaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobUUID', full_name='resAdmin.releaseRequest.jobUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='occupier', full_name='resAdmin.releaseRequest.occupier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_RELEASERESPONSE = _descriptor.Descriptor(
  name='releaseResponse',
  full_name='resAdmin.releaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='resAdmin.releaseResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=117,
)


_RESERVEREQUEST = _descriptor.Descriptor(
  name='reserveRequest',
  full_name='resAdmin.reserveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resNum', full_name='resAdmin.reserveRequest.resNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='occupier', full_name='resAdmin.reserveRequest.occupier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserveSeconds', full_name='resAdmin.reserveRequest.reserveSeconds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jobUUID', full_name='resAdmin.reserveRequest.jobUUID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=210,
)


_RESERVERESPONSE = _descriptor.Descriptor(
  name='reserveResponse',
  full_name='resAdmin.reserveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='resAdmin.reserveResponse.retCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IPList', full_name='resAdmin.reserveResponse.IPList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESERVERESPONSE_RETCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=352,
)


_RESSTATUSINFO = _descriptor.Descriptor(
  name='resStatusInfo',
  full_name='resAdmin.resStatusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resType', full_name='resAdmin.resStatusInfo.resType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resIP', full_name='resAdmin.resStatusInfo.resIP', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resStatus', full_name='resAdmin.resStatusInfo.resStatus', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='occupier', full_name='resAdmin.resStatusInfo.occupier', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='occupyExpireTimeStamp', full_name='resAdmin.resStatusInfo.occupyExpireTimeStamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='resAdmin.resStatusInfo.timestamp', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jobUUID', full_name='resAdmin.resStatusInfo.jobUUID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESSTATUSINFO_RESSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=624,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='resAdmin.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=633,
)


_RESGETRESPOOLINFO = _descriptor.Descriptor(
  name='resGetResPoolInfo',
  full_name='resAdmin.resGetResPoolInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='resAdmin.resGetResPoolInfo.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='free', full_name='resAdmin.resGetResPoolInfo.free', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=683,
)


_RESAGENTINFO = _descriptor.Descriptor(
  name='resAgentInfo',
  full_name='resAdmin.resAgentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resIP', full_name='resAdmin.resAgentInfo.resIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=714,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='heartBeat',
  full_name='resAdmin.heartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isAlive', full_name='resAdmin.heartBeat.isAlive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=744,
)

_RESERVERESPONSE.fields_by_name['retCode'].enum_type = _RESERVERESPONSE_RETCODE
_RESERVERESPONSE_RETCODE.containing_type = _RESERVERESPONSE
_RESSTATUSINFO.fields_by_name['resStatus'].enum_type = _RESSTATUSINFO_RESSTATUS
_RESSTATUSINFO_RESSTATUS.containing_type = _RESSTATUSINFO
DESCRIPTOR.message_types_by_name['releaseRequest'] = _RELEASEREQUEST
DESCRIPTOR.message_types_by_name['releaseResponse'] = _RELEASERESPONSE
DESCRIPTOR.message_types_by_name['reserveRequest'] = _RESERVEREQUEST
DESCRIPTOR.message_types_by_name['reserveResponse'] = _RESERVERESPONSE
DESCRIPTOR.message_types_by_name['resStatusInfo'] = _RESSTATUSINFO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['resGetResPoolInfo'] = _RESGETRESPOOLINFO
DESCRIPTOR.message_types_by_name['resAgentInfo'] = _RESAGENTINFO
DESCRIPTOR.message_types_by_name['heartBeat'] = _HEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

releaseRequest = _reflection.GeneratedProtocolMessageType('releaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _RELEASEREQUEST,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.releaseRequest)
  ))
_sym_db.RegisterMessage(releaseRequest)

releaseResponse = _reflection.GeneratedProtocolMessageType('releaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _RELEASERESPONSE,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.releaseResponse)
  ))
_sym_db.RegisterMessage(releaseResponse)

reserveRequest = _reflection.GeneratedProtocolMessageType('reserveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESERVEREQUEST,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.reserveRequest)
  ))
_sym_db.RegisterMessage(reserveRequest)

reserveResponse = _reflection.GeneratedProtocolMessageType('reserveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESERVERESPONSE,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.reserveResponse)
  ))
_sym_db.RegisterMessage(reserveResponse)

resStatusInfo = _reflection.GeneratedProtocolMessageType('resStatusInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESSTATUSINFO,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.resStatusInfo)
  ))
_sym_db.RegisterMessage(resStatusInfo)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.Empty)
  ))
_sym_db.RegisterMessage(Empty)

resGetResPoolInfo = _reflection.GeneratedProtocolMessageType('resGetResPoolInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESGETRESPOOLINFO,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.resGetResPoolInfo)
  ))
_sym_db.RegisterMessage(resGetResPoolInfo)

resAgentInfo = _reflection.GeneratedProtocolMessageType('resAgentInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESAGENTINFO,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.resAgentInfo)
  ))
_sym_db.RegisterMessage(resAgentInfo)

heartBeat = _reflection.GeneratedProtocolMessageType('heartBeat', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEAT,
  __module__ = 'resManager_pb2'
  # @@protoc_insertion_point(class_scope:resAdmin.heartBeat)
  ))
_sym_db.RegisterMessage(heartBeat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.resAdmin.resManagerB\nresManagerP\001\242\002\002RA'))

_RESMANAGER = _descriptor.ServiceDescriptor(
  name='resManager',
  full_name='resAdmin.resManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=747,
  serialized_end=1105,
  methods=[
  _descriptor.MethodDescriptor(
    name='reserveWindows',
    full_name='resAdmin.resManager.reserveWindows',
    index=0,
    containing_service=None,
    input_type=_RESERVEREQUEST,
    output_type=_RESERVERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='releaseWindows',
    full_name='resAdmin.resManager.releaseWindows',
    index=1,
    containing_service=None,
    input_type=_RELEASEREQUEST,
    output_type=_RELEASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateResPool',
    full_name='resAdmin.resManager.updateResPool',
    index=2,
    containing_service=None,
    input_type=_RESSTATUSINFO,
    output_type=_RESSTATUSINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getResPoolInfo',
    full_name='resAdmin.resManager.getResPoolInfo',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESGETRESPOOLINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkHeartBeat',
    full_name='resAdmin.resManager.checkHeartBeat',
    index=4,
    containing_service=None,
    input_type=_RESAGENTINFO,
    output_type=_HEARTBEAT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESMANAGER)

DESCRIPTOR.services_by_name['resManager'] = _RESMANAGER

# @@protoc_insertion_point(module_scope)
