ONE_DAY_IN_SECONDS = 60 * 60 * 24

DEFAULT_RES_ADMIN_SERVER_IP = "10.1.8.88"
DEFAULT_RES_ADMIN_SERVER_PORT = "11830"
DEFAULT_RES_ADMIN_SERVER_ADDR = "%s:%s" % (DEFAULT_RES_ADMIN_SERVER_IP,DEFAULT_RES_ADMIN_SERVER_PORT)

POLL_DURATION = 5
CACHE_SIZE = 6

DB_USER = 'amtbot'
DB_PASSWORD = 'amtbot'
DB_HOST='10.1.11.0'
DB_NAME='meetingMgr'